[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)] [string]$ProductIdentityPath,
    [Parameter(Mandatory, Position = 1)] [ValidatePattern('^[0-9]+\.[0-9]+\.[0-9]+$')] [string]$ProductVersion,
    [Parameter(Mandatory, Position = 2)] [string]$GeneratedOutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-AbsolutePath([string]$Path) { [System.IO.Path]::GetFullPath($Path) }

function Test-ByteArrayEqual([byte[]]$Left, [byte[]]$Right) {
    if ($Left.Length -ne $Right.Length) { return $false }
    for ($i = 0; $i -lt $Left.Length; $i++) { if ($Left[$i] -ne $Right[$i]) { return $false } }
    return $true
}

function Convert-GuidToRfc4122Bytes([guid]$Guid) {
    $native = $Guid.ToByteArray()
    return [byte[]]@($native[3], $native[2], $native[1], $native[0], $native[5], $native[4], $native[7], $native[6],
        $native[8], $native[9], $native[10], $native[11], $native[12], $native[13], $native[14], $native[15])
}

function Convert-Rfc4122BytesToGuid([byte[]]$Bytes) {
    if ($Bytes.Length -ne 16) { throw 'UUID requires exactly 16 bytes' }
    return [guid]::new([byte[]]@($Bytes[3], $Bytes[2], $Bytes[1], $Bytes[0], $Bytes[5], $Bytes[4], $Bytes[7], $Bytes[6],
        $Bytes[8], $Bytes[9], $Bytes[10], $Bytes[11], $Bytes[12], $Bytes[13], $Bytes[14], $Bytes[15]))
}

function Get-UuidV5([guid]$Namespace, [string]$Name) {
    $namespaceBytes = Convert-GuidToRfc4122Bytes $Namespace
    $nameBytes = [System.Text.Encoding]::UTF8.GetBytes($Name)
    $input = New-Object byte[] ($namespaceBytes.Length + $nameBytes.Length)
    [Array]::Copy($namespaceBytes, 0, $input, 0, $namespaceBytes.Length)
    [Array]::Copy($nameBytes, 0, $input, $namespaceBytes.Length, $nameBytes.Length)
    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try { $hash = $sha1.ComputeHash($input) } finally { $sha1.Dispose() }
    $uuid = [byte[]]$hash[0..15]
    $uuid[6] = [byte](($uuid[6] -band 0x0f) -bor 0x50)
    $uuid[8] = [byte](($uuid[8] -band 0x3f) -bor 0x80)
    Convert-Rfc4122BytesToGuid $uuid
}

function Read-IdentityValue([string]$Text, [string]$Name) {
    $pattern = '<\?define\s+' + [regex]::Escape($Name) + '\s*=\s*"([^"]+)"\s*\?>'
    $matches = [regex]::Matches($Text, $pattern)
    if ($matches.Count -ne 1) { throw "ProductIdentity.wxi must define '$Name' exactly once" }
    $matches[0].Groups[1].Value.Trim()
}

function Assert-WindowsInstallerVersion([string]$Version) {
    $parts = $Version.Split('.')
    if ([int]$parts[0] -gt 255 -or [int]$parts[1] -gt 255 -or [int]$parts[2] -gt 65535) {
        throw "ProductVersion '$Version' exceeds Windows Installer three-part version limits"
    }
}

$identityPath = Get-AbsolutePath $ProductIdentityPath
$output = Get-AbsolutePath $GeneratedOutputPath
if (!(Test-Path -LiteralPath $identityPath -PathType Leaf)) { throw "Product identity input is missing: $identityPath" }
Assert-WindowsInstallerVersion $ProductVersion

$before = [System.IO.File]::ReadAllBytes($identityPath)
$utf8 = New-Object System.Text.UTF8Encoding($false)
$text = [System.IO.File]::ReadAllText($identityPath, $utf8)
$identity = [ordered]@{
    ProductLineKey = Read-IdentityValue $text 'VoxMicProductLineKey'
    UpgradeCode = Read-IdentityValue $text 'VoxMicUpgradeCode'
    ProductCodeNamespace = Read-IdentityValue $text 'VoxMicProductCodeNamespace'
    ComponentNamespace = Read-IdentityValue $text 'VoxMicComponentNamespace'
}
$expected = [ordered]@{
    ProductLineKey = 'stable|x64|perMachine'
    UpgradeCode = 'BCD6404E-75C3-47AF-A16E-223633CBB8A7'
    ProductCodeNamespace = '7643ED05-ADFC-4207-A2D0-12D52C7F9C29'
    ComponentNamespace = '0ABD2E9B-5F96-4DB0-B19F-7D1B92412AC9'
}
foreach ($name in $expected.Keys) {
    if (![string]::Equals($identity[$name], $expected[$name], [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "ProductIdentity.wxi immutable value '$name' does not match the established VoxMic MSI contract"
    }
}
foreach ($name in @('UpgradeCode', 'ProductCodeNamespace', 'ComponentNamespace')) {
    try { [void]([guid]$identity[$name]) } catch { throw "ProductIdentity.wxi '$name' is not a GUID" }
}

$productCode = Get-UuidV5 ([guid]$identity.ProductCodeNamespace) ("{0}|{1}" -f $identity.ProductLineKey, $ProductVersion)
$installFolderGuid = Get-UuidV5 ([guid]$identity.ComponentNamespace) ("{0}|installer:install-folder-registry" -f $identity.ProductLineKey)
$shortcutGuid = Get-UuidV5 ([guid]$identity.ComponentNamespace) ("{0}|installer:start-menu-shortcut" -f $identity.ProductLineKey)

$content = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_wix_product_instance.ps1. Do not hand-edit. -->
<Include xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <?define VoxMicProductVersion = "$ProductVersion" ?>
  <?define VoxMicProductCode = "{$($productCode.ToString().ToUpperInvariant())}" ?>
  <?define VoxMicInstallFolderRegistryComponentGuid = "{$($installFolderGuid.ToString().ToUpperInvariant())}" ?>
  <?define VoxMicStartMenuShortcutComponentGuid = "{$($shortcutGuid.ToString().ToUpperInvariant())}" ?>
</Include>
"@

New-Item -ItemType Directory -Path ([System.IO.Path]::GetDirectoryName($output)) -Force | Out-Null
$temporary = "$output.tmp"
[System.IO.File]::WriteAllText($temporary, $content, $utf8)
Move-Item -LiteralPath $temporary -Destination $output -Force

$after = [System.IO.File]::ReadAllBytes($identityPath)
if (!(Test-ByteArrayEqual $before $after)) { throw 'ProductIdentity.wxi changed during MSI generation' }
Write-Output ("Generated WiX product instance: version={0}, productCode={1}" -f $ProductVersion, $productCode.ToString().ToUpperInvariant())
